### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by yniwly43** [agamez/libwa-qt4#1]
Hi there,

When I register using this project, I successfully get a number/password. After a while, though, typically a few hours of using the library to connect, my number just gets blocked.

Any idea what's up?

**Comment by agamez** [comment]
You're probably talking about Yappari. This is not its repository.
If that's the case, I refer you to http://talk.maemo.org/showthread.php?t=94465

**Comment by yniwly43** [comment]
Okay, I read it. Interesting. Also read your update.

I am not sure how you mean to solve this, though... Yowsup and Chat-API have both become basically unusable due to being automatically blocked. There has been a massive protocol change in Whatsapp.

While it is possible to see the protocol (managed to beat the SSL pinning), the encryption is tough to beat and it's a very complex project to do alone.

I'd love to help with this, but I really would love some pointers.. :)

**Comment by samuelg78** [comment]
@yniwly43 Hi......how you managed to beat the SSL pinning? I tried to use bluestack and fiddler..... but its getting nothing

**Comment by agamez** [comment]
I don't... I'm using S40 decompiled code and other implementations as
reference (yowsup, chat-api, etc)

2016-04-28 7:52 GMT+02:00 samuelg78 notifications@github.com:

> @yniwly43 https://github.com/yniwly43 Hi......how you managed to beat
> the SSL pinning? I tried to use bluestack and fiddler..... but its getting
> nothing
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/agamez/libwa-qt4/issues/1#issuecomment-215316553

## 

Álvaro Gámez Machado
